load("@main//toolchain_data:toolchains_collection_registrar.bzl", "register_toolchains_in_build_file")
load("@generated_toolchain//:id_function.bzl", "get_toolchain_data_id")

register_toolchains_in_build_file("@//:commands_toolchain_type", get_toolchain_data_id)
